# Generated by Django 4.1.13 on 2025-10-15 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=200)),
                ('company', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('registration', 'Registration'), ('greeting', 'Avatar Greeting'), ('video', 'Video Playback'), ('mcq', 'MCQ Exam'), ('feedback', 'Feedback'), ('qa', 'Q&A Session'), ('completed', 'Completed')], default='registration', max_length=20)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('video_completed', models.BooleanField(default=False)),
                ('mcq_score', models.IntegerField(blank=True, null=True)),
                ('mcq_total', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.trainee')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
